name: text_cipher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.2.0
  custom_sliding_segmented_control: ^1.8.5
  el_tooltip: ^2.2.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.4
  go_router: ^17.2.1
  google_fonts: ^8.0.2
  syncfusion_flutter_core: ^33.1.49
  syncfusion_flutter_sliders: ^33.1.49
  window_manager: ^0.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
